
version: 2

models:
    - name: EMPLOYEE
      description: "A starter dbt model employee"
      database: FIVETRAN_TESTING_DATABASE
      schema: PUBLIC_PUBLIC
      tables: EMPLOYEE
      columns:
          - name: emp_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
          - name: role
            description: "The role column of employee table"
          - name: emp_name
            description: "The employee name column of employee table"
           