
version: 2

models:
    - name: EMPLOYEE
      description: "A starter dbt model"
      columns:
          - name: emp_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null