
version: 2

models:
    - name: EMPLOYEE
      description: "A starter dbt model employee"
      database: FIVETRAN_TESTING_DATABASE
      schema: PUBLIC_PUBLIC
      tables: EMPLOYEE
      columns:
          - name: emp_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
            meta:
              dimension:
                label: 'emp_id' # this is the label you'll see in Lightdash
                description: 'My custom description'
          - name: role
            description: "The role column of employee table"
            meta:
              dimension:
                label: 'role' # this is the label you'll see in Lightdash
                description: 'My custom description'
          - name: emp_name
            description: "The employee name column of employee table"
            meta:
              dimension:
                label: 'emp_name' # this is the label you'll see in Lightdash
                description: 'My custom description'